server:
  port:6060

spring:
  datasource:
    url: jdbc:mysql:///spring_boot_crawler?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true # 让model和数据库表结构一致。当model改变，JPA也改变表字段（生产环境不要这样设置）
    show-sql: true
    database: mysql

# 配置信息
com:
  example:
    config:
      siteCharset: utf-8
      urlDetails: http://fund.eastmoney.com/{jfId}.html